name: Libft_CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v7

            - name: Install Dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y build-essential cmake valgrind ${{ matrix.compiler }}

            - name: Norminette
              uses: 42School/norminette@3.3.59
              with:
                args: src/ bonus/ includes/ '-RCheckForbiddenSourceHeader'

            - name: make
              run: |
                make

            - name: test
              run: |
                cd script
                make
                ./test

            - name: valgrind-check
              run: |
                valgrind ./test
